### ISSUE TITLE
写了这么多,提几点意见给你

### ISSUE THREAD

**Issue by SERE026** [hsweb-pro/hsweb-payment#1]
1.项目太多,部署麻烦,
2.生成的数据字段类型有问题(mysql)
3.关于业务中嵌入的eventPublisher.publishEvent 并没有发现自定义监听器,这么做完全没有意义

**Comment by SERE026** [comment]
商户和渠道还有用户 之间的关系也没有搞清楚,没有明确的说明

**Comment by zhou-hao** [comment]
第一个问题。maven多模块项目，实际只需要启动hsweb-payment-assemble 即可
第二个问题。请使用mysql5.7
第三个问题。事件监听使用的是@EventListener注解，大部分事件都有监听着，事件驱动的意义是解耦，事件生产者本来就不应该关心有没有消费者。
最后，本项目为纯开源项目，没时间搞文档，见谅。
