### ISSUE TITLE
密码

### ISSUE THREAD

**Issue by wgq126** [hsweb-pro/hsweb-payment#2]
嘿！docker启动后，hsweb-payment的后台管理密码是什么？

**Comment by zhou-hao** [comment]
admim admin------------------ 原始邮件 ------------------
发件人: "wgq126"<notifications@github.com>
发送时间: 2019年11月23日(星期六) 晚上6:25
收件人: "hsweb-pro/hsweb-payment"<hsweb-payment@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [hsweb-pro/hsweb-payment] 密码 (#2)



嘿！docker启动后，hsweb-payment的后台管理密码是什么？
 
&mdash;
